spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/SOSDJavaCh01?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl